name: employee_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  floor: ^1.2.0
  get: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.4
  lints: 1.0.1
  floor_generator: ^1.2.0
  build_runner: ^2.1.7
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

